models:
- columns:
  - description: Blockchain
    name: blockchain
    tests: []
  - description: System contract address
    name: address
    tests: []
  - description: Label name
    name: name
    tests: []
  - description: Label category
    name: category
    tests: []
  - description: Wizard(s) contributing to labels
    name: contributor
    tests: []
  - description: How were labels generated (could be static or query)
    name: source
    tests: []
  - description: When were labels created
    name: created_at
    tests: []
  - description: When were labels updated for the last time
    name: updated_at
    tests: []
  - description: Name of the label model sourced from
    name: model_name
    tests: []
  - description: Type of label (see labels overall readme)
    name: label_type
    tests: []
  config:
    tags:
    - labels
    - system
    - addresses
    - exclude
    - optimism
    - arbitrum
    - solana
  description: Contract addresses for system transactions on various blockchains.
    These should be excluded in 'real usage' measurements.
  meta:
    blockchain: optimism, arbitrum, solana
    contributors: msilb7
    project: system_addresses
    sector: labels
  name: labels_system_addresses
  tests: []
version: 2
