models:
- columns:
  - description: Blockchain
    name: blockchain
    tests: []
  - description: Address of known MEV wallet
    name: address
    tests: []
  - description: Label name of MEV address
    name: name
    tests: []
  - description: Label category
    name: category
    tests: []
  - description: Wizard(s) contributing to labels
    name: contributor
    tests: []
  - description: How were labels generated (could be static or query)
    name: source
    tests: []
  - description: When were labels created
    name: created_at
    tests: []
  - description: When were labels updated for the last time
    name: updated_at
    tests: []
  - description: Name of the label model sourced from
    name: model_name
    tests: []
  - description: Type of label (see labels overall readme)
    name: label_type
    tests: []
  config:
    tags:
    - labels
    - ethereum
    - MEV
  description: Known MEV wallets on Ethereum
  meta:
    blockchain: ethereum, optimism, polygon, arbitrum
    contributors: hildobby
    project: mev
    sector: labels
  name: labels_mev_ethereum
  tests: []
version: 2
