models:
- columns:
  - description: Blockchain
    name: blockchain
    tests: []
  - description: Label address
    name: address
    tests: []
  - description: Label name of the contract (e.g., Ethereum Miner)
    name: name
    tests: []
  - description: Label category
    name: category
    tests: []
  - description: Wizard(s) contributing to labels
    name: contributor
    tests: []
  - description: How were labels generated (could be static or query)
    name: source
    tests: []
  - description: When were labels created
    name: created_at
    tests: []
  - description: When were labels updated for the last time
    name: updated_at
    tests: []
  - description: Name of the label model sourced from
    name: model_name
    tests: []
  - description: Type of label (see labels overall readme)
    name: label_type
    tests: []
  config:
    tags:
    - query
    - labels
    - miners
  description: Dune contracts query labels across chains
  meta:
    blockchain: ethereum, arbitrum, gnosis, optimism, bnb, avalanche_c, fantom, polygon
    category: miners
    contributors: soispoke
    sector: labels
  name: labels_miners
  tests: []
version: 2
