models:
- columns:
  - description: Blockchain
    name: blockchain
    tests: []
  - description: Address of trader
    name: address
    tests: []
  - description: Label name
    name: name
    tests: []
  - description: Label category
    name: category
    tests: []
  - description: Wizard(s) contributing to labels
    name: contributor
    tests: []
  - description: How were labels generated (query)
    name: source
    tests: []
  - description: When were labels created
    name: created_at
    tests: []
  - description: When were labels updated for the last time
    name: updated_at
    tests: []
  - description: Name of the label model sourced from
    name: model_name
    tests: []
  - description: Type of label (see labels overall readme)
    name: label_type
    tests: []
  config:
    tags:
    - labels
    - cross-chain evm
    - average_trade_values
    - dex
    - dex_aggregator
  description: Trader average trade values for addresses who use dex and dex aggregators
  meta:
    blockchain: ethereum, arbitrum, gnosis, optimism, polygon, fantom
    category: dex
    contributors: gentrexha, Henrystats
    sector: labels
  name: labels_average_trade_values
  tests: []
version: 2
