models:
- columns:
  - description: Blockchain
    name: blockchain
    tests: []
  - description: Label address
    name: address
    tests: []
  - description: Label name
    name: name
    tests: []
  - description: Label category
    name: category
    tests:
    - accepted_values:
        values:
        - infrastructure
  - description: Wizard(s) contributing to labels
    name: contributor
    tests: []
  - description: How were labels generated (query)
    name: source
    tests: []
  - description: When were labels created
    name: created_at
    tests: []
  - description: When were labels updated for the last time
    name: updated_at
    tests: []
  - description: Name of the label model sourced from
    name: model_name
    tests: []
  - description: Type of label (see labels overall readme)
    name: label_type
    tests: []
  config:
    tags:
    - labels
    - infrastructure
    - mev
    - staking
    - system
    - validator
  description: all infrastructure labels
  meta:
    blockchain: ethereum, polygon, gnosis
    category: infrastructure
    contributors: ilemi, hildobby
    sector: labels
  name: labels_infrastructure
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - address
      - name
      - category
      - model_name
      - blockchain
version: 2
