models:
- columns:
  - description: Blockchain
    name: blockchain
    tests: []
  - description: Burn address
    name: address
    tests: []
  - description: Label name
    name: name
    tests: []
  - description: Label category
    name: category
    tests: []
  - description: Wizard(s) contributing to labels
    name: contributor
    tests: []
  - description: How were labels generated (could be static or query)
    name: source
    tests: []
  - description: When were labels created
    name: created_at
    tests: []
  - description: When were labels updated for the last time
    name: updated_at
    tests: []
  - description: Name of the label model sourced from
    name: model_name
    tests: []
  - description: Type of label (see labels overall readme)
    name: label_type
    tests: []
  config:
    tags:
    - labels
    - burn_addresses
    - erc20
    - ethereum
  description: Burn addresses
  meta:
    blockchain: ethereum
    contributors: hildobby
    project: burn_addresses
    sector: labels
  name: labels_burn_addresses
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - address
      - blockchain
version: 2
