models:
- columns:
  - &id001
    description: Blockchain
    name: blockchain
    tests: []
  - &id002
    description: Address of known token smart contract
    name: address
    tests: []
  - &id003
    description: Token standard of the smart contract
    name: name
    tests: []
  - &id004
    description: Label category
    name: category
    tests: []
  - &id005
    description: Wizard(s) contributing to labels
    name: contributor
    tests: []
  - &id006
    description: How were labels generated (could be static or query)
    name: source
    tests: []
  - &id007
    description: When were labels created
    name: created_at
    tests: []
  - &id008
    description: When were labels updated for the last time
    name: updated_at
    tests: []
  - &id009
    description: Name of the label model sourced from
    name: model_name
    tests: []
  - &id010
    description: Type of label (see labels overall readme)
    name: label_type
    tests: []
  config:
    tags:
    - labels
    - arbitrum
    - token_standards
    - erc20
    - erc721
    - erc1155
  description: Smart contract token standards on Arbitrum
  meta:
    blockchain: arbitrum
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_arbitrum
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - avalanche_c
    - token_standards
    - erc20
    - erc721
    - erc1155
  description: Smart contract token standards on Avalanche
  meta:
    blockchain: avalanche_c
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_avalanche_c
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - bnb
    - token_standards
    - bep20
    - bep721
    - bep1155
  description: Smart contract token standards on BNB
  meta:
    blockchain: bnb
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_bnb
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - ethereum
    - token_standards
    - erc20
    - erc721
    - erc1155
  description: Smart contract token standards on Arbitrum
  meta:
    blockchain: ethereum
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_ethereum
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - fantom
    - token_standards
    - erc20
    - erc721
    - erc1155
  description: Smart contract token standards on Arbitrum
  meta:
    blockchain: fantom
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_fantom
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - gnosis
    - token_standards
    - erc20
    - erc721
    - erc1155
  description: Smart contract token standards on Gnosis
  meta:
    blockchain: gnosis
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_gnosis
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - goerli
    - token_standards
    - erc20
    - erc721
    - erc1155
  description: Smart contract token standards on Goerli
  meta:
    blockchain: goerli
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_goerli
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - optimism
    - token_standards
    - erc20
    - erc721
    - erc1155
  description: Smart contract token standards on Optimism
  meta:
    blockchain: optimism
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_optimism
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - polygon
    - token_standards
    - erc20
    - erc721
    - erc1155
  description: Smart contract token standards on Polygon
  meta:
    blockchain: polygon
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards_polygon
  tests: []
- columns:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  config:
    tags:
    - labels
    - arbitrum
    - avalanche_c
    - bnb
    - ethereum
    - fantom
    - gnosis
    - goerli
    - optimism
    - polygon
    - token_standards
    - erc20
    - erc721
    - erc1155
    - bep20
    - bep721
    - bep1155
  description: Smart contract token standards across blockchains
  meta:
    blockchain: arbitrum, avalanche_c, bnb, ethereum, fantom, gnosis, goerli, optimism,
      polygon
    contributors: hildobby
    project: token_standards
    sector: labels
  name: labels_token_standards
  tests: []
version: 2
