models:
- columns:
  - description: Address of known flashloan user wallet
    name: address
    tests: []
  - description: Label category
    name: category
    tests: []
  - description: Name of the label model sourced from
    name: model_name
    tests: []
  - description: Blockchain
    name: blockchain
    tests: []
  - description: Label name of the contract (e.g., Aave v3 Flashloan User)
    name: name
    tests: []
  - description: Wizard(s) contributing to labels
    name: contributor
    tests: []
  - description: How were labels generated (could be static or query)
    name: source
    tests: []
  - description: When were labels created
    name: created_at
    tests: []
  - description: When were labels updated for the last time
    name: updated_at
    tests: []
  - description: Type of label (see labels overall readme)
    name: label_type
    tests: []
  config:
    tags:
    - labels
    - ethereum
    - flashloans
  description: Known flashloan users on Ethereum
  meta:
    blockchain: ethereum
    contributors: niftytable
    project: flashloans
    sector: labels
  name: labels_flashloans_ethereum
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - address
      - name
version: 2
