sources:
- name: flashbots
  tables:
  - columns:
    - name: account_address
    - name: block_number
    - name: end_amount
    - name: error
    - name: id
    - name: profit_amount
    - name: profit_token_address
    - name: protocols
    - name: start_amount
    - name: transaction_hash
    name: arbitrages
version: 2
